// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface A_ArrayExprOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.A_ArrayExpr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pg_query.Node elements = 1 [json_name = "elements"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getElementsList();
  /**
   * <code>repeated .pg_query.Node elements = 1 [json_name = "elements"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getElements(int index);
  /**
   * <code>repeated .pg_query.Node elements = 1 [json_name = "elements"];</code>
   */
  int getElementsCount();
  /**
   * <code>repeated .pg_query.Node elements = 1 [json_name = "elements"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getElementsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node elements = 1 [json_name = "elements"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getElementsOrBuilder(
      int index);

  /**
   * <code>int32 list_start = 2 [json_name = "list_start"];</code>
   * @return The listStart.
   */
  int getListStart();

  /**
   * <code>int32 list_end = 3 [json_name = "list_end"];</code>
   * @return The listEnd.
   */
  int getListEnd();

  /**
   * <code>int32 location = 4 [json_name = "location"];</code>
   * @return The location.
   */
  int getLocation();
}
