// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface AccessPrivOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.AccessPriv)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string priv_name = 1 [json_name = "priv_name"];</code>
   * @return The privName.
   */
  java.lang.String getPrivName();
  /**
   * <code>string priv_name = 1 [json_name = "priv_name"];</code>
   * @return The bytes for privName.
   */
  com.google.protobuf.ByteString
      getPrivNameBytes();

  /**
   * <code>repeated .pg_query.Node cols = 2 [json_name = "cols"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getColsList();
  /**
   * <code>repeated .pg_query.Node cols = 2 [json_name = "cols"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getCols(int index);
  /**
   * <code>repeated .pg_query.Node cols = 2 [json_name = "cols"];</code>
   */
  int getColsCount();
  /**
   * <code>repeated .pg_query.Node cols = 2 [json_name = "cols"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getColsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node cols = 2 [json_name = "cols"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getColsOrBuilder(
      int index);
}
