// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface AlterSystemStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.AlterSystemStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.VariableSetStmt setstmt = 1 [json_name = "setstmt"];</code>
   * @return Whether the setstmt field is set.
   */
  boolean hasSetstmt();
  /**
   * <code>.pg_query.VariableSetStmt setstmt = 1 [json_name = "setstmt"];</code>
   * @return The setstmt.
   */
  com.premiumminds.sonar.postgres.protobuf.VariableSetStmt getSetstmt();
  /**
   * <code>.pg_query.VariableSetStmt setstmt = 1 [json_name = "setstmt"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.VariableSetStmtOrBuilder getSetstmtOrBuilder();
}
