// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface AlterSeqStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.AlterSeqStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.RangeVar sequence = 1 [json_name = "sequence"];</code>
   * @return Whether the sequence field is set.
   */
  boolean hasSequence();
  /**
   * <code>.pg_query.RangeVar sequence = 1 [json_name = "sequence"];</code>
   * @return The sequence.
   */
  com.premiumminds.sonar.postgres.protobuf.RangeVar getSequence();
  /**
   * <code>.pg_query.RangeVar sequence = 1 [json_name = "sequence"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.RangeVarOrBuilder getSequenceOrBuilder();

  /**
   * <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getOptionsList();
  /**
   * <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getOptions(int index);
  /**
   * <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
   */
  int getOptionsCount();
  /**
   * <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getOptionsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getOptionsOrBuilder(
      int index);

  /**
   * <code>bool for_identity = 3 [json_name = "for_identity"];</code>
   * @return The forIdentity.
   */
  boolean getForIdentity();

  /**
   * <code>bool missing_ok = 4 [json_name = "missing_ok"];</code>
   * @return The missingOk.
   */
  boolean getMissingOk();
}
