// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface AlterTSDictionaryStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.AlterTSDictionaryStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pg_query.Node dictname = 1 [json_name = "dictname"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getDictnameList();
  /**
   * <code>repeated .pg_query.Node dictname = 1 [json_name = "dictname"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getDictname(int index);
  /**
   * <code>repeated .pg_query.Node dictname = 1 [json_name = "dictname"];</code>
   */
  int getDictnameCount();
  /**
   * <code>repeated .pg_query.Node dictname = 1 [json_name = "dictname"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getDictnameOrBuilderList();
  /**
   * <code>repeated .pg_query.Node dictname = 1 [json_name = "dictname"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getDictnameOrBuilder(
      int index);

  /**
   * <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getOptionsList();
  /**
   * <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getOptions(int index);
  /**
   * <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
   */
  int getOptionsCount();
  /**
   * <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getOptionsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getOptionsOrBuilder(
      int index);
}
