// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface AlterDatabaseRefreshCollStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.AlterDatabaseRefreshCollStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dbname = 1 [json_name = "dbname"];</code>
   * @return The dbname.
   */
  java.lang.String getDbname();
  /**
   * <code>string dbname = 1 [json_name = "dbname"];</code>
   * @return The bytes for dbname.
   */
  com.google.protobuf.ByteString
      getDbnameBytes();
}
