// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

// Protobuf Java Version: 3.25.1
package com.premiumminds.sonar.postgres.protobuf;

public interface ATAlterConstraintOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.ATAlterConstraint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string conname = 1 [json_name = "conname"];</code>
   * @return The conname.
   */
  java.lang.String getConname();
  /**
   * <code>string conname = 1 [json_name = "conname"];</code>
   * @return The bytes for conname.
   */
  com.google.protobuf.ByteString
      getConnameBytes();

  /**
   * <code>bool alter_enforceability = 2 [json_name = "alterEnforceability"];</code>
   * @return The alterEnforceability.
   */
  boolean getAlterEnforceability();

  /**
   * <code>bool is_enforced = 3 [json_name = "is_enforced"];</code>
   * @return The isEnforced.
   */
  boolean getIsEnforced();

  /**
   * <code>bool alter_deferrability = 4 [json_name = "alterDeferrability"];</code>
   * @return The alterDeferrability.
   */
  boolean getAlterDeferrability();

  /**
   * <code>bool deferrable = 5 [json_name = "deferrable"];</code>
   * @return The deferrable.
   */
  boolean getDeferrable();

  /**
   * <code>bool initdeferred = 6 [json_name = "initdeferred"];</code>
   * @return The initdeferred.
   */
  boolean getInitdeferred();

  /**
   * <code>bool alter_inheritability = 7 [json_name = "alterInheritability"];</code>
   * @return The alterInheritability.
   */
  boolean getAlterInheritability();

  /**
   * <code>bool noinherit = 8 [json_name = "noinherit"];</code>
   * @return The noinherit.
   */
  boolean getNoinherit();
}
