// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

/**
 * Protobuf type {@code pg_query.ATAlterConstraint}
 */
@com.google.protobuf.Generated
public final class ATAlterConstraint extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:pg_query.ATAlterConstraint)
    ATAlterConstraintOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "ATAlterConstraint");
  }
  // Use ATAlterConstraint.newBuilder() to construct.
  private ATAlterConstraint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ATAlterConstraint() {
    conname_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_ATAlterConstraint_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_ATAlterConstraint_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_ATAlterConstraint_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint.class, com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint.Builder.class);
  }

  public static final int CONNAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object conname_ = "";
  /**
   * <code>string conname = 1 [json_name = "conname"];</code>
   * @return The conname.
   */
  @java.lang.Override
  public java.lang.String getConname() {
    java.lang.Object ref = conname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      conname_ = s;
      return s;
    }
  }
  /**
   * <code>string conname = 1 [json_name = "conname"];</code>
   * @return The bytes for conname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConnameBytes() {
    java.lang.Object ref = conname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      conname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALTER_ENFORCEABILITY_FIELD_NUMBER = 2;
  private boolean alterEnforceability_ = false;
  /**
   * <code>bool alter_enforceability = 2 [json_name = "alterEnforceability"];</code>
   * @return The alterEnforceability.
   */
  @java.lang.Override
  public boolean getAlterEnforceability() {
    return alterEnforceability_;
  }

  public static final int IS_ENFORCED_FIELD_NUMBER = 3;
  private boolean isEnforced_ = false;
  /**
   * <code>bool is_enforced = 3 [json_name = "is_enforced"];</code>
   * @return The isEnforced.
   */
  @java.lang.Override
  public boolean getIsEnforced() {
    return isEnforced_;
  }

  public static final int ALTER_DEFERRABILITY_FIELD_NUMBER = 4;
  private boolean alterDeferrability_ = false;
  /**
   * <code>bool alter_deferrability = 4 [json_name = "alterDeferrability"];</code>
   * @return The alterDeferrability.
   */
  @java.lang.Override
  public boolean getAlterDeferrability() {
    return alterDeferrability_;
  }

  public static final int DEFERRABLE_FIELD_NUMBER = 5;
  private boolean deferrable_ = false;
  /**
   * <code>bool deferrable = 5 [json_name = "deferrable"];</code>
   * @return The deferrable.
   */
  @java.lang.Override
  public boolean getDeferrable() {
    return deferrable_;
  }

  public static final int INITDEFERRED_FIELD_NUMBER = 6;
  private boolean initdeferred_ = false;
  /**
   * <code>bool initdeferred = 6 [json_name = "initdeferred"];</code>
   * @return The initdeferred.
   */
  @java.lang.Override
  public boolean getInitdeferred() {
    return initdeferred_;
  }

  public static final int ALTER_INHERITABILITY_FIELD_NUMBER = 7;
  private boolean alterInheritability_ = false;
  /**
   * <code>bool alter_inheritability = 7 [json_name = "alterInheritability"];</code>
   * @return The alterInheritability.
   */
  @java.lang.Override
  public boolean getAlterInheritability() {
    return alterInheritability_;
  }

  public static final int NOINHERIT_FIELD_NUMBER = 8;
  private boolean noinherit_ = false;
  /**
   * <code>bool noinherit = 8 [json_name = "noinherit"];</code>
   * @return The noinherit.
   */
  @java.lang.Override
  public boolean getNoinherit() {
    return noinherit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(conname_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, conname_);
    }
    if (alterEnforceability_ != false) {
      output.writeBool(2, alterEnforceability_);
    }
    if (isEnforced_ != false) {
      output.writeBool(3, isEnforced_);
    }
    if (alterDeferrability_ != false) {
      output.writeBool(4, alterDeferrability_);
    }
    if (deferrable_ != false) {
      output.writeBool(5, deferrable_);
    }
    if (initdeferred_ != false) {
      output.writeBool(6, initdeferred_);
    }
    if (alterInheritability_ != false) {
      output.writeBool(7, alterInheritability_);
    }
    if (noinherit_ != false) {
      output.writeBool(8, noinherit_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(conname_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, conname_);
    }
    if (alterEnforceability_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, alterEnforceability_);
    }
    if (isEnforced_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isEnforced_);
    }
    if (alterDeferrability_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, alterDeferrability_);
    }
    if (deferrable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, deferrable_);
    }
    if (initdeferred_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, initdeferred_);
    }
    if (alterInheritability_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, alterInheritability_);
    }
    if (noinherit_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, noinherit_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint)) {
      return super.equals(obj);
    }
    com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint other = (com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint) obj;

    if (!getConname()
        .equals(other.getConname())) return false;
    if (getAlterEnforceability()
        != other.getAlterEnforceability()) return false;
    if (getIsEnforced()
        != other.getIsEnforced()) return false;
    if (getAlterDeferrability()
        != other.getAlterDeferrability()) return false;
    if (getDeferrable()
        != other.getDeferrable()) return false;
    if (getInitdeferred()
        != other.getInitdeferred()) return false;
    if (getAlterInheritability()
        != other.getAlterInheritability()) return false;
    if (getNoinherit()
        != other.getNoinherit()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONNAME_FIELD_NUMBER;
    hash = (53 * hash) + getConname().hashCode();
    hash = (37 * hash) + ALTER_ENFORCEABILITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAlterEnforceability());
    hash = (37 * hash) + IS_ENFORCED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsEnforced());
    hash = (37 * hash) + ALTER_DEFERRABILITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAlterDeferrability());
    hash = (37 * hash) + DEFERRABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDeferrable());
    hash = (37 * hash) + INITDEFERRED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInitdeferred());
    hash = (37 * hash) + ALTER_INHERITABILITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAlterInheritability());
    hash = (37 * hash) + NOINHERIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNoinherit());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pg_query.ATAlterConstraint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pg_query.ATAlterConstraint)
      com.premiumminds.sonar.postgres.protobuf.ATAlterConstraintOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_ATAlterConstraint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_ATAlterConstraint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint.class, com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint.Builder.class);
    }

    // Construct using com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      conname_ = "";
      alterEnforceability_ = false;
      isEnforced_ = false;
      alterDeferrability_ = false;
      deferrable_ = false;
      initdeferred_ = false;
      alterInheritability_ = false;
      noinherit_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_ATAlterConstraint_descriptor;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint getDefaultInstanceForType() {
      return com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint.getDefaultInstance();
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint build() {
      com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint buildPartial() {
      com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint result = new com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.conname_ = conname_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.alterEnforceability_ = alterEnforceability_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.isEnforced_ = isEnforced_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.alterDeferrability_ = alterDeferrability_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.deferrable_ = deferrable_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.initdeferred_ = initdeferred_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.alterInheritability_ = alterInheritability_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.noinherit_ = noinherit_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint) {
        return mergeFrom((com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint other) {
      if (other == com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint.getDefaultInstance()) return this;
      if (!other.getConname().isEmpty()) {
        conname_ = other.conname_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAlterEnforceability() != false) {
        setAlterEnforceability(other.getAlterEnforceability());
      }
      if (other.getIsEnforced() != false) {
        setIsEnforced(other.getIsEnforced());
      }
      if (other.getAlterDeferrability() != false) {
        setAlterDeferrability(other.getAlterDeferrability());
      }
      if (other.getDeferrable() != false) {
        setDeferrable(other.getDeferrable());
      }
      if (other.getInitdeferred() != false) {
        setInitdeferred(other.getInitdeferred());
      }
      if (other.getAlterInheritability() != false) {
        setAlterInheritability(other.getAlterInheritability());
      }
      if (other.getNoinherit() != false) {
        setNoinherit(other.getNoinherit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              conname_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              alterEnforceability_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              isEnforced_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              alterDeferrability_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              deferrable_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              initdeferred_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              alterInheritability_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              noinherit_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object conname_ = "";
    /**
     * <code>string conname = 1 [json_name = "conname"];</code>
     * @return The conname.
     */
    public java.lang.String getConname() {
      java.lang.Object ref = conname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string conname = 1 [json_name = "conname"];</code>
     * @return The bytes for conname.
     */
    public com.google.protobuf.ByteString
        getConnameBytes() {
      java.lang.Object ref = conname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string conname = 1 [json_name = "conname"];</code>
     * @param value The conname to set.
     * @return This builder for chaining.
     */
    public Builder setConname(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      conname_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string conname = 1 [json_name = "conname"];</code>
     * @return This builder for chaining.
     */
    public Builder clearConname() {
      conname_ = getDefaultInstance().getConname();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string conname = 1 [json_name = "conname"];</code>
     * @param value The bytes for conname to set.
     * @return This builder for chaining.
     */
    public Builder setConnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      conname_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean alterEnforceability_ ;
    /**
     * <code>bool alter_enforceability = 2 [json_name = "alterEnforceability"];</code>
     * @return The alterEnforceability.
     */
    @java.lang.Override
    public boolean getAlterEnforceability() {
      return alterEnforceability_;
    }
    /**
     * <code>bool alter_enforceability = 2 [json_name = "alterEnforceability"];</code>
     * @param value The alterEnforceability to set.
     * @return This builder for chaining.
     */
    public Builder setAlterEnforceability(boolean value) {

      alterEnforceability_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool alter_enforceability = 2 [json_name = "alterEnforceability"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAlterEnforceability() {
      bitField0_ = (bitField0_ & ~0x00000002);
      alterEnforceability_ = false;
      onChanged();
      return this;
    }

    private boolean isEnforced_ ;
    /**
     * <code>bool is_enforced = 3 [json_name = "is_enforced"];</code>
     * @return The isEnforced.
     */
    @java.lang.Override
    public boolean getIsEnforced() {
      return isEnforced_;
    }
    /**
     * <code>bool is_enforced = 3 [json_name = "is_enforced"];</code>
     * @param value The isEnforced to set.
     * @return This builder for chaining.
     */
    public Builder setIsEnforced(boolean value) {

      isEnforced_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_enforced = 3 [json_name = "is_enforced"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsEnforced() {
      bitField0_ = (bitField0_ & ~0x00000004);
      isEnforced_ = false;
      onChanged();
      return this;
    }

    private boolean alterDeferrability_ ;
    /**
     * <code>bool alter_deferrability = 4 [json_name = "alterDeferrability"];</code>
     * @return The alterDeferrability.
     */
    @java.lang.Override
    public boolean getAlterDeferrability() {
      return alterDeferrability_;
    }
    /**
     * <code>bool alter_deferrability = 4 [json_name = "alterDeferrability"];</code>
     * @param value The alterDeferrability to set.
     * @return This builder for chaining.
     */
    public Builder setAlterDeferrability(boolean value) {

      alterDeferrability_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool alter_deferrability = 4 [json_name = "alterDeferrability"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAlterDeferrability() {
      bitField0_ = (bitField0_ & ~0x00000008);
      alterDeferrability_ = false;
      onChanged();
      return this;
    }

    private boolean deferrable_ ;
    /**
     * <code>bool deferrable = 5 [json_name = "deferrable"];</code>
     * @return The deferrable.
     */
    @java.lang.Override
    public boolean getDeferrable() {
      return deferrable_;
    }
    /**
     * <code>bool deferrable = 5 [json_name = "deferrable"];</code>
     * @param value The deferrable to set.
     * @return This builder for chaining.
     */
    public Builder setDeferrable(boolean value) {

      deferrable_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool deferrable = 5 [json_name = "deferrable"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeferrable() {
      bitField0_ = (bitField0_ & ~0x00000010);
      deferrable_ = false;
      onChanged();
      return this;
    }

    private boolean initdeferred_ ;
    /**
     * <code>bool initdeferred = 6 [json_name = "initdeferred"];</code>
     * @return The initdeferred.
     */
    @java.lang.Override
    public boolean getInitdeferred() {
      return initdeferred_;
    }
    /**
     * <code>bool initdeferred = 6 [json_name = "initdeferred"];</code>
     * @param value The initdeferred to set.
     * @return This builder for chaining.
     */
    public Builder setInitdeferred(boolean value) {

      initdeferred_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool initdeferred = 6 [json_name = "initdeferred"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInitdeferred() {
      bitField0_ = (bitField0_ & ~0x00000020);
      initdeferred_ = false;
      onChanged();
      return this;
    }

    private boolean alterInheritability_ ;
    /**
     * <code>bool alter_inheritability = 7 [json_name = "alterInheritability"];</code>
     * @return The alterInheritability.
     */
    @java.lang.Override
    public boolean getAlterInheritability() {
      return alterInheritability_;
    }
    /**
     * <code>bool alter_inheritability = 7 [json_name = "alterInheritability"];</code>
     * @param value The alterInheritability to set.
     * @return This builder for chaining.
     */
    public Builder setAlterInheritability(boolean value) {

      alterInheritability_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool alter_inheritability = 7 [json_name = "alterInheritability"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAlterInheritability() {
      bitField0_ = (bitField0_ & ~0x00000040);
      alterInheritability_ = false;
      onChanged();
      return this;
    }

    private boolean noinherit_ ;
    /**
     * <code>bool noinherit = 8 [json_name = "noinherit"];</code>
     * @return The noinherit.
     */
    @java.lang.Override
    public boolean getNoinherit() {
      return noinherit_;
    }
    /**
     * <code>bool noinherit = 8 [json_name = "noinherit"];</code>
     * @param value The noinherit to set.
     * @return This builder for chaining.
     */
    public Builder setNoinherit(boolean value) {

      noinherit_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool noinherit = 8 [json_name = "noinherit"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNoinherit() {
      bitField0_ = (bitField0_ & ~0x00000080);
      noinherit_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pg_query.ATAlterConstraint)
  }

  // @@protoc_insertion_point(class_scope:pg_query.ATAlterConstraint)
  private static final com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint();
  }

  public static com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ATAlterConstraint>
      PARSER = new com.google.protobuf.AbstractParser<ATAlterConstraint>() {
    @java.lang.Override
    public ATAlterConstraint parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ATAlterConstraint> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ATAlterConstraint> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.ATAlterConstraint getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

