// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface BitStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.BitString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * string 
   * </pre>
   *
   * <code>string bsval = 1;</code>
   * @return The bsval.
   */
  java.lang.String getBsval();
  /**
   * <pre>
   * string 
   * </pre>
   *
   * <code>string bsval = 1;</code>
   * @return The bytes for bsval.
   */
  com.google.protobuf.ByteString
      getBsvalBytes();
}
