// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

// Protobuf Java Version: 3.25.1
package com.premiumminds.sonar.postgres.protobuf;

/**
 * Protobuf enum {@code pg_query.CompareType}
 */
public enum CompareType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>COMPARE_TYPE_UNDEFINED = 0;</code>
   */
  COMPARE_TYPE_UNDEFINED(0),
  /**
   * <code>COMPARE_INVALID = 1;</code>
   */
  COMPARE_INVALID(1),
  /**
   * <code>COMPARE_LT = 2;</code>
   */
  COMPARE_LT(2),
  /**
   * <code>COMPARE_LE = 3;</code>
   */
  COMPARE_LE(3),
  /**
   * <code>COMPARE_EQ = 4;</code>
   */
  COMPARE_EQ(4),
  /**
   * <code>COMPARE_GE = 5;</code>
   */
  COMPARE_GE(5),
  /**
   * <code>COMPARE_GT = 6;</code>
   */
  COMPARE_GT(6),
  /**
   * <code>COMPARE_NE = 7;</code>
   */
  COMPARE_NE(7),
  /**
   * <code>COMPARE_OVERLAP = 8;</code>
   */
  COMPARE_OVERLAP(8),
  /**
   * <code>COMPARE_CONTAINED_BY = 9;</code>
   */
  COMPARE_CONTAINED_BY(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>COMPARE_TYPE_UNDEFINED = 0;</code>
   */
  public static final int COMPARE_TYPE_UNDEFINED_VALUE = 0;
  /**
   * <code>COMPARE_INVALID = 1;</code>
   */
  public static final int COMPARE_INVALID_VALUE = 1;
  /**
   * <code>COMPARE_LT = 2;</code>
   */
  public static final int COMPARE_LT_VALUE = 2;
  /**
   * <code>COMPARE_LE = 3;</code>
   */
  public static final int COMPARE_LE_VALUE = 3;
  /**
   * <code>COMPARE_EQ = 4;</code>
   */
  public static final int COMPARE_EQ_VALUE = 4;
  /**
   * <code>COMPARE_GE = 5;</code>
   */
  public static final int COMPARE_GE_VALUE = 5;
  /**
   * <code>COMPARE_GT = 6;</code>
   */
  public static final int COMPARE_GT_VALUE = 6;
  /**
   * <code>COMPARE_NE = 7;</code>
   */
  public static final int COMPARE_NE_VALUE = 7;
  /**
   * <code>COMPARE_OVERLAP = 8;</code>
   */
  public static final int COMPARE_OVERLAP_VALUE = 8;
  /**
   * <code>COMPARE_CONTAINED_BY = 9;</code>
   */
  public static final int COMPARE_CONTAINED_BY_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CompareType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CompareType forNumber(int value) {
    switch (value) {
      case 0: return COMPARE_TYPE_UNDEFINED;
      case 1: return COMPARE_INVALID;
      case 2: return COMPARE_LT;
      case 3: return COMPARE_LE;
      case 4: return COMPARE_EQ;
      case 5: return COMPARE_GE;
      case 6: return COMPARE_GT;
      case 7: return COMPARE_NE;
      case 8: return COMPARE_OVERLAP;
      case 9: return COMPARE_CONTAINED_BY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CompareType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CompareType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CompareType>() {
          public CompareType findValueByNumber(int number) {
            return CompareType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.getDescriptor().getEnumTypes().get(70);
  }

  private static final CompareType[] VALUES = values();

  public static CompareType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CompareType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pg_query.CompareType)
}

