// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface ConstraintsSetStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.ConstraintsSetStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pg_query.Node constraints = 1 [json_name = "constraints"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getConstraintsList();
  /**
   * <code>repeated .pg_query.Node constraints = 1 [json_name = "constraints"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getConstraints(int index);
  /**
   * <code>repeated .pg_query.Node constraints = 1 [json_name = "constraints"];</code>
   */
  int getConstraintsCount();
  /**
   * <code>repeated .pg_query.Node constraints = 1 [json_name = "constraints"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getConstraintsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node constraints = 1 [json_name = "constraints"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getConstraintsOrBuilder(
      int index);

  /**
   * <code>bool deferred = 2 [json_name = "deferred"];</code>
   * @return The deferred.
   */
  boolean getDeferred();
}
