// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface CreateAmStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.CreateAmStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string amname = 1 [json_name = "amname"];</code>
   * @return The amname.
   */
  java.lang.String getAmname();
  /**
   * <code>string amname = 1 [json_name = "amname"];</code>
   * @return The bytes for amname.
   */
  com.google.protobuf.ByteString
      getAmnameBytes();

  /**
   * <code>repeated .pg_query.Node handler_name = 2 [json_name = "handler_name"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getHandlerNameList();
  /**
   * <code>repeated .pg_query.Node handler_name = 2 [json_name = "handler_name"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getHandlerName(int index);
  /**
   * <code>repeated .pg_query.Node handler_name = 2 [json_name = "handler_name"];</code>
   */
  int getHandlerNameCount();
  /**
   * <code>repeated .pg_query.Node handler_name = 2 [json_name = "handler_name"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getHandlerNameOrBuilderList();
  /**
   * <code>repeated .pg_query.Node handler_name = 2 [json_name = "handler_name"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getHandlerNameOrBuilder(
      int index);

  /**
   * <code>string amtype = 3 [json_name = "amtype"];</code>
   * @return The amtype.
   */
  java.lang.String getAmtype();
  /**
   * <code>string amtype = 3 [json_name = "amtype"];</code>
   * @return The bytes for amtype.
   */
  com.google.protobuf.ByteString
      getAmtypeBytes();
}
