// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface CreateOpFamilyStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.CreateOpFamilyStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pg_query.Node opfamilyname = 1 [json_name = "opfamilyname"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getOpfamilynameList();
  /**
   * <code>repeated .pg_query.Node opfamilyname = 1 [json_name = "opfamilyname"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getOpfamilyname(int index);
  /**
   * <code>repeated .pg_query.Node opfamilyname = 1 [json_name = "opfamilyname"];</code>
   */
  int getOpfamilynameCount();
  /**
   * <code>repeated .pg_query.Node opfamilyname = 1 [json_name = "opfamilyname"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getOpfamilynameOrBuilderList();
  /**
   * <code>repeated .pg_query.Node opfamilyname = 1 [json_name = "opfamilyname"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getOpfamilynameOrBuilder(
      int index);

  /**
   * <code>string amname = 2 [json_name = "amname"];</code>
   * @return The amname.
   */
  java.lang.String getAmname();
  /**
   * <code>string amname = 2 [json_name = "amname"];</code>
   * @return The bytes for amname.
   */
  com.google.protobuf.ByteString
      getAmnameBytes();
}
