// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface DeclareCursorStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.DeclareCursorStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string portalname = 1 [json_name = "portalname"];</code>
   * @return The portalname.
   */
  java.lang.String getPortalname();
  /**
   * <code>string portalname = 1 [json_name = "portalname"];</code>
   * @return The bytes for portalname.
   */
  com.google.protobuf.ByteString
      getPortalnameBytes();

  /**
   * <code>int32 options = 2 [json_name = "options"];</code>
   * @return The options.
   */
  int getOptions();

  /**
   * <code>.pg_query.Node query = 3 [json_name = "query"];</code>
   * @return Whether the query field is set.
   */
  boolean hasQuery();
  /**
   * <code>.pg_query.Node query = 3 [json_name = "query"];</code>
   * @return The query.
   */
  com.premiumminds.sonar.postgres.protobuf.Node getQuery();
  /**
   * <code>.pg_query.Node query = 3 [json_name = "query"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getQueryOrBuilder();
}
