// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface DropTableSpaceStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.DropTableSpaceStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tablespacename = 1 [json_name = "tablespacename"];</code>
   * @return The tablespacename.
   */
  java.lang.String getTablespacename();
  /**
   * <code>string tablespacename = 1 [json_name = "tablespacename"];</code>
   * @return The bytes for tablespacename.
   */
  com.google.protobuf.ByteString
      getTablespacenameBytes();

  /**
   * <code>bool missing_ok = 2 [json_name = "missing_ok"];</code>
   * @return The missingOk.
   */
  boolean getMissingOk();
}
