// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface DropUserMappingStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.DropUserMappingStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.RoleSpec user = 1 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.pg_query.RoleSpec user = 1 [json_name = "user"];</code>
   * @return The user.
   */
  com.premiumminds.sonar.postgres.protobuf.RoleSpec getUser();
  /**
   * <code>.pg_query.RoleSpec user = 1 [json_name = "user"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.RoleSpecOrBuilder getUserOrBuilder();

  /**
   * <code>string servername = 2 [json_name = "servername"];</code>
   * @return The servername.
   */
  java.lang.String getServername();
  /**
   * <code>string servername = 2 [json_name = "servername"];</code>
   * @return The bytes for servername.
   */
  com.google.protobuf.ByteString
      getServernameBytes();

  /**
   * <code>bool missing_ok = 3 [json_name = "missing_ok"];</code>
   * @return The missingOk.
   */
  boolean getMissingOk();
}
