// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface ExecuteStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.ExecuteStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .pg_query.Node params = 2 [json_name = "params"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getParamsList();
  /**
   * <code>repeated .pg_query.Node params = 2 [json_name = "params"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getParams(int index);
  /**
   * <code>repeated .pg_query.Node params = 2 [json_name = "params"];</code>
   */
  int getParamsCount();
  /**
   * <code>repeated .pg_query.Node params = 2 [json_name = "params"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getParamsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node params = 2 [json_name = "params"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getParamsOrBuilder(
      int index);
}
