// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface IntegerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.Integer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * machine integer 
   * </pre>
   *
   * <code>int32 ival = 1;</code>
   * @return The ival.
   */
  int getIval();
}
