// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface IntListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.IntList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pg_query.Node items = 1;</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getItemsList();
  /**
   * <code>repeated .pg_query.Node items = 1;</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getItems(int index);
  /**
   * <code>repeated .pg_query.Node items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .pg_query.Node items = 1;</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node items = 1;</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getItemsOrBuilder(
      int index);
}
