// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface JsonFormatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.JsonFormat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.JsonFormatType format_type = 1 [json_name = "format_type"];</code>
   * @return The enum numeric value on the wire for formatType.
   */
  int getFormatTypeValue();
  /**
   * <code>.pg_query.JsonFormatType format_type = 1 [json_name = "format_type"];</code>
   * @return The formatType.
   */
  com.premiumminds.sonar.postgres.protobuf.JsonFormatType getFormatType();

  /**
   * <code>.pg_query.JsonEncoding encoding = 2 [json_name = "encoding"];</code>
   * @return The enum numeric value on the wire for encoding.
   */
  int getEncodingValue();
  /**
   * <code>.pg_query.JsonEncoding encoding = 2 [json_name = "encoding"];</code>
   * @return The encoding.
   */
  com.premiumminds.sonar.postgres.protobuf.JsonEncoding getEncoding();

  /**
   * <code>int32 location = 3 [json_name = "location"];</code>
   * @return The location.
   */
  int getLocation();
}
