// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface JsonKeyValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.JsonKeyValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.Node key = 1 [json_name = "key"];</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>.pg_query.Node key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  com.premiumminds.sonar.postgres.protobuf.Node getKey();
  /**
   * <code>.pg_query.Node key = 1 [json_name = "key"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getKeyOrBuilder();

  /**
   * <code>.pg_query.JsonValueExpr value = 2 [json_name = "value"];</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.pg_query.JsonValueExpr value = 2 [json_name = "value"];</code>
   * @return The value.
   */
  com.premiumminds.sonar.postgres.protobuf.JsonValueExpr getValue();
  /**
   * <code>.pg_query.JsonValueExpr value = 2 [json_name = "value"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.JsonValueExprOrBuilder getValueOrBuilder();
}
