// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface JsonScalarExprOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.JsonScalarExpr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.Node expr = 1 [json_name = "expr"];</code>
   * @return Whether the expr field is set.
   */
  boolean hasExpr();
  /**
   * <code>.pg_query.Node expr = 1 [json_name = "expr"];</code>
   * @return The expr.
   */
  com.premiumminds.sonar.postgres.protobuf.Node getExpr();
  /**
   * <code>.pg_query.Node expr = 1 [json_name = "expr"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getExprOrBuilder();

  /**
   * <code>.pg_query.JsonOutput output = 2 [json_name = "output"];</code>
   * @return Whether the output field is set.
   */
  boolean hasOutput();
  /**
   * <code>.pg_query.JsonOutput output = 2 [json_name = "output"];</code>
   * @return The output.
   */
  com.premiumminds.sonar.postgres.protobuf.JsonOutput getOutput();
  /**
   * <code>.pg_query.JsonOutput output = 2 [json_name = "output"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.JsonOutputOrBuilder getOutputOrBuilder();

  /**
   * <code>int32 location = 3 [json_name = "location"];</code>
   * @return The location.
   */
  int getLocation();
}
