// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface JsonArrayAggOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.JsonArrayAgg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.JsonAggConstructor constructor = 1 [json_name = "constructor"];</code>
   * @return Whether the constructor field is set.
   */
  boolean hasConstructor();
  /**
   * <code>.pg_query.JsonAggConstructor constructor = 1 [json_name = "constructor"];</code>
   * @return The constructor.
   */
  com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor getConstructor();
  /**
   * <code>.pg_query.JsonAggConstructor constructor = 1 [json_name = "constructor"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.JsonAggConstructorOrBuilder getConstructorOrBuilder();

  /**
   * <code>.pg_query.JsonValueExpr arg = 2 [json_name = "arg"];</code>
   * @return Whether the arg field is set.
   */
  boolean hasArg();
  /**
   * <code>.pg_query.JsonValueExpr arg = 2 [json_name = "arg"];</code>
   * @return The arg.
   */
  com.premiumminds.sonar.postgres.protobuf.JsonValueExpr getArg();
  /**
   * <code>.pg_query.JsonValueExpr arg = 2 [json_name = "arg"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.JsonValueExprOrBuilder getArgOrBuilder();

  /**
   * <code>bool absent_on_null = 3 [json_name = "absent_on_null"];</code>
   * @return The absentOnNull.
   */
  boolean getAbsentOnNull();
}
