// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface JsonArgumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.JsonArgument)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.JsonValueExpr val = 1 [json_name = "val"];</code>
   * @return Whether the val field is set.
   */
  boolean hasVal();
  /**
   * <code>.pg_query.JsonValueExpr val = 1 [json_name = "val"];</code>
   * @return The val.
   */
  com.premiumminds.sonar.postgres.protobuf.JsonValueExpr getVal();
  /**
   * <code>.pg_query.JsonValueExpr val = 1 [json_name = "val"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.JsonValueExprOrBuilder getValOrBuilder();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
