// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface JsonTablePathSpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.JsonTablePathSpec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.Node string = 1 [json_name = "string"];</code>
   * @return Whether the string field is set.
   */
  boolean hasString();
  /**
   * <code>.pg_query.Node string = 1 [json_name = "string"];</code>
   * @return The string.
   */
  com.premiumminds.sonar.postgres.protobuf.Node getString();
  /**
   * <code>.pg_query.Node string = 1 [json_name = "string"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getStringOrBuilder();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 name_location = 3 [json_name = "name_location"];</code>
   * @return The nameLocation.
   */
  int getNameLocation();

  /**
   * <code>int32 location = 4 [json_name = "location"];</code>
   * @return The location.
   */
  int getLocation();
}
