// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface ListenStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.ListenStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string conditionname = 1 [json_name = "conditionname"];</code>
   * @return The conditionname.
   */
  java.lang.String getConditionname();
  /**
   * <code>string conditionname = 1 [json_name = "conditionname"];</code>
   * @return The bytes for conditionname.
   */
  com.google.protobuf.ByteString
      getConditionnameBytes();
}
