// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface ObjectWithArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.ObjectWithArgs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pg_query.Node objname = 1 [json_name = "objname"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getObjnameList();
  /**
   * <code>repeated .pg_query.Node objname = 1 [json_name = "objname"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getObjname(int index);
  /**
   * <code>repeated .pg_query.Node objname = 1 [json_name = "objname"];</code>
   */
  int getObjnameCount();
  /**
   * <code>repeated .pg_query.Node objname = 1 [json_name = "objname"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getObjnameOrBuilderList();
  /**
   * <code>repeated .pg_query.Node objname = 1 [json_name = "objname"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getObjnameOrBuilder(
      int index);

  /**
   * <code>repeated .pg_query.Node objargs = 2 [json_name = "objargs"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getObjargsList();
  /**
   * <code>repeated .pg_query.Node objargs = 2 [json_name = "objargs"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getObjargs(int index);
  /**
   * <code>repeated .pg_query.Node objargs = 2 [json_name = "objargs"];</code>
   */
  int getObjargsCount();
  /**
   * <code>repeated .pg_query.Node objargs = 2 [json_name = "objargs"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getObjargsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node objargs = 2 [json_name = "objargs"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getObjargsOrBuilder(
      int index);

  /**
   * <code>repeated .pg_query.Node objfuncargs = 3 [json_name = "objfuncargs"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getObjfuncargsList();
  /**
   * <code>repeated .pg_query.Node objfuncargs = 3 [json_name = "objfuncargs"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getObjfuncargs(int index);
  /**
   * <code>repeated .pg_query.Node objfuncargs = 3 [json_name = "objfuncargs"];</code>
   */
  int getObjfuncargsCount();
  /**
   * <code>repeated .pg_query.Node objfuncargs = 3 [json_name = "objfuncargs"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getObjfuncargsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node objfuncargs = 3 [json_name = "objfuncargs"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getObjfuncargsOrBuilder(
      int index);

  /**
   * <code>bool args_unspecified = 4 [json_name = "args_unspecified"];</code>
   * @return The argsUnspecified.
   */
  boolean getArgsUnspecified();
}
