// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface ParamRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.ParamRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1 [json_name = "number"];</code>
   * @return The number.
   */
  int getNumber();

  /**
   * <code>int32 location = 2 [json_name = "location"];</code>
   * @return The location.
   */
  int getLocation();
}
