// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface PartitionSpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.PartitionSpec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.PartitionStrategy strategy = 1 [json_name = "strategy"];</code>
   * @return The enum numeric value on the wire for strategy.
   */
  int getStrategyValue();
  /**
   * <code>.pg_query.PartitionStrategy strategy = 1 [json_name = "strategy"];</code>
   * @return The strategy.
   */
  com.premiumminds.sonar.postgres.protobuf.PartitionStrategy getStrategy();

  /**
   * <code>repeated .pg_query.Node part_params = 2 [json_name = "partParams"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getPartParamsList();
  /**
   * <code>repeated .pg_query.Node part_params = 2 [json_name = "partParams"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getPartParams(int index);
  /**
   * <code>repeated .pg_query.Node part_params = 2 [json_name = "partParams"];</code>
   */
  int getPartParamsCount();
  /**
   * <code>repeated .pg_query.Node part_params = 2 [json_name = "partParams"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getPartParamsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node part_params = 2 [json_name = "partParams"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getPartParamsOrBuilder(
      int index);

  /**
   * <code>int32 location = 3 [json_name = "location"];</code>
   * @return The location.
   */
  int getLocation();
}
