// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface PartitionCmdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.PartitionCmd)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.RangeVar name = 1 [json_name = "name"];</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>.pg_query.RangeVar name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  com.premiumminds.sonar.postgres.protobuf.RangeVar getName();
  /**
   * <code>.pg_query.RangeVar name = 1 [json_name = "name"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.RangeVarOrBuilder getNameOrBuilder();

  /**
   * <code>.pg_query.PartitionBoundSpec bound = 2 [json_name = "bound"];</code>
   * @return Whether the bound field is set.
   */
  boolean hasBound();
  /**
   * <code>.pg_query.PartitionBoundSpec bound = 2 [json_name = "bound"];</code>
   * @return The bound.
   */
  com.premiumminds.sonar.postgres.protobuf.PartitionBoundSpec getBound();
  /**
   * <code>.pg_query.PartitionBoundSpec bound = 2 [json_name = "bound"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.PartitionBoundSpecOrBuilder getBoundOrBuilder();

  /**
   * <code>bool concurrent = 3 [json_name = "concurrent"];</code>
   * @return The concurrent.
   */
  boolean getConcurrent();
}
