// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface RangeSubselectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.RangeSubselect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lateral = 1 [json_name = "lateral"];</code>
   * @return The lateral.
   */
  boolean getLateral();

  /**
   * <code>.pg_query.Node subquery = 2 [json_name = "subquery"];</code>
   * @return Whether the subquery field is set.
   */
  boolean hasSubquery();
  /**
   * <code>.pg_query.Node subquery = 2 [json_name = "subquery"];</code>
   * @return The subquery.
   */
  com.premiumminds.sonar.postgres.protobuf.Node getSubquery();
  /**
   * <code>.pg_query.Node subquery = 2 [json_name = "subquery"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getSubqueryOrBuilder();

  /**
   * <code>.pg_query.Alias alias = 3 [json_name = "alias"];</code>
   * @return Whether the alias field is set.
   */
  boolean hasAlias();
  /**
   * <code>.pg_query.Alias alias = 3 [json_name = "alias"];</code>
   * @return The alias.
   */
  com.premiumminds.sonar.postgres.protobuf.Alias getAlias();
  /**
   * <code>.pg_query.Alias alias = 3 [json_name = "alias"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.AliasOrBuilder getAliasOrBuilder();
}
