// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface ReturningExprOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.ReturningExpr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
   * @return Whether the xpr field is set.
   */
  boolean hasXpr();
  /**
   * <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
   * @return The xpr.
   */
  com.premiumminds.sonar.postgres.protobuf.Node getXpr();
  /**
   * <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getXprOrBuilder();

  /**
   * <code>int32 retlevelsup = 2 [json_name = "retlevelsup"];</code>
   * @return The retlevelsup.
   */
  int getRetlevelsup();

  /**
   * <code>bool retold = 3 [json_name = "retold"];</code>
   * @return The retold.
   */
  boolean getRetold();

  /**
   * <code>.pg_query.Node retexpr = 4 [json_name = "retexpr"];</code>
   * @return Whether the retexpr field is set.
   */
  boolean hasRetexpr();
  /**
   * <code>.pg_query.Node retexpr = 4 [json_name = "retexpr"];</code>
   * @return The retexpr.
   */
  com.premiumminds.sonar.postgres.protobuf.Node getRetexpr();
  /**
   * <code>.pg_query.Node retexpr = 4 [json_name = "retexpr"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getRetexprOrBuilder();
}
