// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface ReturningClauseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.ReturningClause)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getOptionsList();
  /**
   * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getOptions(int index);
  /**
   * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
   */
  int getOptionsCount();
  /**
   * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getOptionsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getOptionsOrBuilder(
      int index);

  /**
   * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getExprsList();
  /**
   * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getExprs(int index);
  /**
   * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
   */
  int getExprsCount();
  /**
   * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getExprsOrBuilderList();
  /**
   * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getExprsOrBuilder(
      int index);
}
