// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

// Protobuf Java Version: 3.25.1
package com.premiumminds.sonar.postgres.protobuf;

/**
 * Protobuf type {@code pg_query.ReturningClause}
 */
public final class ReturningClause extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pg_query.ReturningClause)
    ReturningClauseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReturningClause.newBuilder() to construct.
  private ReturningClause(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReturningClause() {
    options_ = java.util.Collections.emptyList();
    exprs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReturningClause();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_ReturningClause_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_ReturningClause_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.premiumminds.sonar.postgres.protobuf.ReturningClause.class, com.premiumminds.sonar.postgres.protobuf.ReturningClause.Builder.class);
  }

  public static final int OPTIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> options_;
  /**
   * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getOptionsList() {
    return options_;
  }
  /**
   * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
   */
  @java.lang.Override
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }

  public static final int EXPRS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> exprs_;
  /**
   * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
   */
  @java.lang.Override
  public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getExprsList() {
    return exprs_;
  }
  /**
   * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getExprsOrBuilderList() {
    return exprs_;
  }
  /**
   * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
   */
  @java.lang.Override
  public int getExprsCount() {
    return exprs_.size();
  }
  /**
   * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getExprs(int index) {
    return exprs_.get(index);
  }
  /**
   * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getExprsOrBuilder(
      int index) {
    return exprs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < options_.size(); i++) {
      output.writeMessage(1, options_.get(i));
    }
    for (int i = 0; i < exprs_.size(); i++) {
      output.writeMessage(2, exprs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < options_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, options_.get(i));
    }
    for (int i = 0; i < exprs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, exprs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.premiumminds.sonar.postgres.protobuf.ReturningClause)) {
      return super.equals(obj);
    }
    com.premiumminds.sonar.postgres.protobuf.ReturningClause other = (com.premiumminds.sonar.postgres.protobuf.ReturningClause) obj;

    if (!getOptionsList()
        .equals(other.getOptionsList())) return false;
    if (!getExprsList()
        .equals(other.getExprsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOptionsCount() > 0) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptionsList().hashCode();
    }
    if (getExprsCount() > 0) {
      hash = (37 * hash) + EXPRS_FIELD_NUMBER;
      hash = (53 * hash) + getExprsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.premiumminds.sonar.postgres.protobuf.ReturningClause prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pg_query.ReturningClause}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pg_query.ReturningClause)
      com.premiumminds.sonar.postgres.protobuf.ReturningClauseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_ReturningClause_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_ReturningClause_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.premiumminds.sonar.postgres.protobuf.ReturningClause.class, com.premiumminds.sonar.postgres.protobuf.ReturningClause.Builder.class);
    }

    // Construct using com.premiumminds.sonar.postgres.protobuf.ReturningClause.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
      } else {
        options_ = null;
        optionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (exprsBuilder_ == null) {
        exprs_ = java.util.Collections.emptyList();
      } else {
        exprs_ = null;
        exprsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_ReturningClause_descriptor;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.ReturningClause getDefaultInstanceForType() {
      return com.premiumminds.sonar.postgres.protobuf.ReturningClause.getDefaultInstance();
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.ReturningClause build() {
      com.premiumminds.sonar.postgres.protobuf.ReturningClause result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.ReturningClause buildPartial() {
      com.premiumminds.sonar.postgres.protobuf.ReturningClause result = new com.premiumminds.sonar.postgres.protobuf.ReturningClause(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.premiumminds.sonar.postgres.protobuf.ReturningClause result) {
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          options_ = java.util.Collections.unmodifiableList(options_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.options_ = options_;
      } else {
        result.options_ = optionsBuilder_.build();
      }
      if (exprsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          exprs_ = java.util.Collections.unmodifiableList(exprs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.exprs_ = exprs_;
      } else {
        result.exprs_ = exprsBuilder_.build();
      }
    }

    private void buildPartial0(com.premiumminds.sonar.postgres.protobuf.ReturningClause result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.premiumminds.sonar.postgres.protobuf.ReturningClause) {
        return mergeFrom((com.premiumminds.sonar.postgres.protobuf.ReturningClause)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.premiumminds.sonar.postgres.protobuf.ReturningClause other) {
      if (other == com.premiumminds.sonar.postgres.protobuf.ReturningClause.getDefaultInstance()) return this;
      if (optionsBuilder_ == null) {
        if (!other.options_.isEmpty()) {
          if (options_.isEmpty()) {
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOptionsIsMutable();
            options_.addAll(other.options_);
          }
          onChanged();
        }
      } else {
        if (!other.options_.isEmpty()) {
          if (optionsBuilder_.isEmpty()) {
            optionsBuilder_.dispose();
            optionsBuilder_ = null;
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000001);
            optionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOptionsFieldBuilder() : null;
          } else {
            optionsBuilder_.addAllMessages(other.options_);
          }
        }
      }
      if (exprsBuilder_ == null) {
        if (!other.exprs_.isEmpty()) {
          if (exprs_.isEmpty()) {
            exprs_ = other.exprs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureExprsIsMutable();
            exprs_.addAll(other.exprs_);
          }
          onChanged();
        }
      } else {
        if (!other.exprs_.isEmpty()) {
          if (exprsBuilder_.isEmpty()) {
            exprsBuilder_.dispose();
            exprsBuilder_ = null;
            exprs_ = other.exprs_;
            bitField0_ = (bitField0_ & ~0x00000002);
            exprsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExprsFieldBuilder() : null;
          } else {
            exprsBuilder_.addAllMessages(other.exprs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.premiumminds.sonar.postgres.protobuf.Node m =
                  input.readMessage(
                      com.premiumminds.sonar.postgres.protobuf.Node.parser(),
                      extensionRegistry);
              if (optionsBuilder_ == null) {
                ensureOptionsIsMutable();
                options_.add(m);
              } else {
                optionsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              com.premiumminds.sonar.postgres.protobuf.Node m =
                  input.readMessage(
                      com.premiumminds.sonar.postgres.protobuf.Node.parser(),
                      extensionRegistry);
              if (exprsBuilder_ == null) {
                ensureExprsIsMutable();
                exprs_.add(m);
              } else {
                exprsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> options_ =
      java.util.Collections.emptyList();
    private void ensureOptionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        options_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>(options_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> optionsBuilder_;

    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getOptionsList() {
      if (optionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(options_);
      } else {
        return optionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public int getOptionsCount() {
      if (optionsBuilder_ == null) {
        return options_.size();
      } else {
        return optionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getOptions(int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);
      } else {
        return optionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.set(index, value);
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.set(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public Builder addOptions(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(index, value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public Builder addOptions(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends com.premiumminds.sonar.postgres.protobuf.Node> values) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, options_);
        onChanged();
      } else {
        optionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        optionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public Builder removeOptions(int index) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.remove(index);
        onChanged();
      } else {
        optionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getOptionsOrBuilder(
        int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);  } else {
        return optionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
         getOptionsOrBuilderList() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(options_);
      }
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addOptionsBuilder() {
      return getOptionsFieldBuilder().addBuilder(
          com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().addBuilder(
          index, com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node.Builder> 
         getOptionsBuilderList() {
      return getOptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                options_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> exprs_ =
      java.util.Collections.emptyList();
    private void ensureExprsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        exprs_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>(exprs_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> exprsBuilder_;

    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getExprsList() {
      if (exprsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(exprs_);
      } else {
        return exprsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public int getExprsCount() {
      if (exprsBuilder_ == null) {
        return exprs_.size();
      } else {
        return exprsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getExprs(int index) {
      if (exprsBuilder_ == null) {
        return exprs_.get(index);
      } else {
        return exprsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public Builder setExprs(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (exprsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExprsIsMutable();
        exprs_.set(index, value);
        onChanged();
      } else {
        exprsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public Builder setExprs(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (exprsBuilder_ == null) {
        ensureExprsIsMutable();
        exprs_.set(index, builderForValue.build());
        onChanged();
      } else {
        exprsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public Builder addExprs(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (exprsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExprsIsMutable();
        exprs_.add(value);
        onChanged();
      } else {
        exprsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public Builder addExprs(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (exprsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExprsIsMutable();
        exprs_.add(index, value);
        onChanged();
      } else {
        exprsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public Builder addExprs(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (exprsBuilder_ == null) {
        ensureExprsIsMutable();
        exprs_.add(builderForValue.build());
        onChanged();
      } else {
        exprsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public Builder addExprs(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (exprsBuilder_ == null) {
        ensureExprsIsMutable();
        exprs_.add(index, builderForValue.build());
        onChanged();
      } else {
        exprsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public Builder addAllExprs(
        java.lang.Iterable<? extends com.premiumminds.sonar.postgres.protobuf.Node> values) {
      if (exprsBuilder_ == null) {
        ensureExprsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, exprs_);
        onChanged();
      } else {
        exprsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public Builder clearExprs() {
      if (exprsBuilder_ == null) {
        exprs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        exprsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public Builder removeExprs(int index) {
      if (exprsBuilder_ == null) {
        ensureExprsIsMutable();
        exprs_.remove(index);
        onChanged();
      } else {
        exprsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getExprsBuilder(
        int index) {
      return getExprsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getExprsOrBuilder(
        int index) {
      if (exprsBuilder_ == null) {
        return exprs_.get(index);  } else {
        return exprsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
         getExprsOrBuilderList() {
      if (exprsBuilder_ != null) {
        return exprsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(exprs_);
      }
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addExprsBuilder() {
      return getExprsFieldBuilder().addBuilder(
          com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addExprsBuilder(
        int index) {
      return getExprsFieldBuilder().addBuilder(
          index, com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node exprs = 2 [json_name = "exprs"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node.Builder> 
         getExprsBuilderList() {
      return getExprsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getExprsFieldBuilder() {
      if (exprsBuilder_ == null) {
        exprsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                exprs_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        exprs_ = null;
      }
      return exprsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pg_query.ReturningClause)
  }

  // @@protoc_insertion_point(class_scope:pg_query.ReturningClause)
  private static final com.premiumminds.sonar.postgres.protobuf.ReturningClause DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.premiumminds.sonar.postgres.protobuf.ReturningClause();
  }

  public static com.premiumminds.sonar.postgres.protobuf.ReturningClause getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReturningClause>
      PARSER = new com.google.protobuf.AbstractParser<ReturningClause>() {
    @java.lang.Override
    public ReturningClause parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReturningClause> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReturningClause> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.ReturningClause getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

