// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

// Protobuf Java Version: 3.25.1
package com.premiumminds.sonar.postgres.protobuf;

/**
 * Protobuf enum {@code pg_query.ReturningOptionKind}
 */
public enum ReturningOptionKind
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RETURNING_OPTION_KIND_UNDEFINED = 0;</code>
   */
  RETURNING_OPTION_KIND_UNDEFINED(0),
  /**
   * <code>RETURNING_OPTION_OLD = 1;</code>
   */
  RETURNING_OPTION_OLD(1),
  /**
   * <code>RETURNING_OPTION_NEW = 2;</code>
   */
  RETURNING_OPTION_NEW(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>RETURNING_OPTION_KIND_UNDEFINED = 0;</code>
   */
  public static final int RETURNING_OPTION_KIND_UNDEFINED_VALUE = 0;
  /**
   * <code>RETURNING_OPTION_OLD = 1;</code>
   */
  public static final int RETURNING_OPTION_OLD_VALUE = 1;
  /**
   * <code>RETURNING_OPTION_NEW = 2;</code>
   */
  public static final int RETURNING_OPTION_NEW_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ReturningOptionKind valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ReturningOptionKind forNumber(int value) {
    switch (value) {
      case 0: return RETURNING_OPTION_KIND_UNDEFINED;
      case 1: return RETURNING_OPTION_OLD;
      case 2: return RETURNING_OPTION_NEW;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ReturningOptionKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ReturningOptionKind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ReturningOptionKind>() {
          public ReturningOptionKind findValueByNumber(int number) {
            return ReturningOptionKind.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.getDescriptor().getEnumTypes().get(14);
  }

  private static final ReturningOptionKind[] VALUES = values();

  public static ReturningOptionKind valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ReturningOptionKind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pg_query.ReturningOptionKind)
}

