// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface ReturningOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.ReturningOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.ReturningOptionKind option = 1 [json_name = "option"];</code>
   * @return The enum numeric value on the wire for option.
   */
  int getOptionValue();
  /**
   * <code>.pg_query.ReturningOptionKind option = 1 [json_name = "option"];</code>
   * @return The option.
   */
  com.premiumminds.sonar.postgres.protobuf.ReturningOptionKind getOption();

  /**
   * <code>string value = 2 [json_name = "value"];</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2 [json_name = "value"];</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>int32 location = 3 [json_name = "location"];</code>
   * @return The location.
   */
  int getLocation();
}
