// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface ScanResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.ScanResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>repeated .pg_query.ScanToken tokens = 2;</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.ScanToken> 
      getTokensList();
  /**
   * <code>repeated .pg_query.ScanToken tokens = 2;</code>
   */
  com.premiumminds.sonar.postgres.protobuf.ScanToken getTokens(int index);
  /**
   * <code>repeated .pg_query.ScanToken tokens = 2;</code>
   */
  int getTokensCount();
  /**
   * <code>repeated .pg_query.ScanToken tokens = 2;</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.ScanTokenOrBuilder> 
      getTokensOrBuilderList();
  /**
   * <code>repeated .pg_query.ScanToken tokens = 2;</code>
   */
  com.premiumminds.sonar.postgres.protobuf.ScanTokenOrBuilder getTokensOrBuilder(
      int index);
}
