// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface StringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.String)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * string 
   * </pre>
   *
   * <code>string sval = 1;</code>
   * @return The sval.
   */
  java.lang.String getSval();
  /**
   * <pre>
   * string 
   * </pre>
   *
   * <code>string sval = 1;</code>
   * @return The bytes for sval.
   */
  com.google.protobuf.ByteString
      getSvalBytes();
}
