// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

// Protobuf Java Version: 3.25.1
package com.premiumminds.sonar.postgres.protobuf;

public interface SummaryResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.SummaryResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pg_query.SummaryResult.Table tables = 1;</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.SummaryResult.Table> 
      getTablesList();
  /**
   * <code>repeated .pg_query.SummaryResult.Table tables = 1;</code>
   */
  com.premiumminds.sonar.postgres.protobuf.SummaryResult.Table getTables(int index);
  /**
   * <code>repeated .pg_query.SummaryResult.Table tables = 1;</code>
   */
  int getTablesCount();
  /**
   * <code>repeated .pg_query.SummaryResult.Table tables = 1;</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.SummaryResult.TableOrBuilder> 
      getTablesOrBuilderList();
  /**
   * <code>repeated .pg_query.SummaryResult.Table tables = 1;</code>
   */
  com.premiumminds.sonar.postgres.protobuf.SummaryResult.TableOrBuilder getTablesOrBuilder(
      int index);

  /**
   * <pre>
   * The value here is the table name (i.e. schema.table or just table).
   * </pre>
   *
   * <code>map&lt;string, string&gt; aliases = 2;</code>
   */
  int getAliasesCount();
  /**
   * <pre>
   * The value here is the table name (i.e. schema.table or just table).
   * </pre>
   *
   * <code>map&lt;string, string&gt; aliases = 2;</code>
   */
  boolean containsAliases(
      java.lang.String key);
  /**
   * Use {@link #getAliasesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAliases();
  /**
   * <pre>
   * The value here is the table name (i.e. schema.table or just table).
   * </pre>
   *
   * <code>map&lt;string, string&gt; aliases = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAliasesMap();
  /**
   * <pre>
   * The value here is the table name (i.e. schema.table or just table).
   * </pre>
   *
   * <code>map&lt;string, string&gt; aliases = 2;</code>
   */
  /* nullable */
java.lang.String getAliasesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * The value here is the table name (i.e. schema.table or just table).
   * </pre>
   *
   * <code>map&lt;string, string&gt; aliases = 2;</code>
   */
  java.lang.String getAliasesOrThrow(
      java.lang.String key);

  /**
   * <code>repeated string cte_names = 3;</code>
   * @return A list containing the cteNames.
   */
  java.util.List<java.lang.String>
      getCteNamesList();
  /**
   * <code>repeated string cte_names = 3;</code>
   * @return The count of cteNames.
   */
  int getCteNamesCount();
  /**
   * <code>repeated string cte_names = 3;</code>
   * @param index The index of the element to return.
   * @return The cteNames at the given index.
   */
  java.lang.String getCteNames(int index);
  /**
   * <code>repeated string cte_names = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cteNames at the given index.
   */
  com.google.protobuf.ByteString
      getCteNamesBytes(int index);

  /**
   * <code>repeated .pg_query.SummaryResult.Function functions = 4;</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.SummaryResult.Function> 
      getFunctionsList();
  /**
   * <code>repeated .pg_query.SummaryResult.Function functions = 4;</code>
   */
  com.premiumminds.sonar.postgres.protobuf.SummaryResult.Function getFunctions(int index);
  /**
   * <code>repeated .pg_query.SummaryResult.Function functions = 4;</code>
   */
  int getFunctionsCount();
  /**
   * <code>repeated .pg_query.SummaryResult.Function functions = 4;</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.SummaryResult.FunctionOrBuilder> 
      getFunctionsOrBuilderList();
  /**
   * <code>repeated .pg_query.SummaryResult.Function functions = 4;</code>
   */
  com.premiumminds.sonar.postgres.protobuf.SummaryResult.FunctionOrBuilder getFunctionsOrBuilder(
      int index);

  /**
   * <code>repeated .pg_query.SummaryResult.FilterColumn filter_columns = 5;</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.SummaryResult.FilterColumn> 
      getFilterColumnsList();
  /**
   * <code>repeated .pg_query.SummaryResult.FilterColumn filter_columns = 5;</code>
   */
  com.premiumminds.sonar.postgres.protobuf.SummaryResult.FilterColumn getFilterColumns(int index);
  /**
   * <code>repeated .pg_query.SummaryResult.FilterColumn filter_columns = 5;</code>
   */
  int getFilterColumnsCount();
  /**
   * <code>repeated .pg_query.SummaryResult.FilterColumn filter_columns = 5;</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.SummaryResult.FilterColumnOrBuilder> 
      getFilterColumnsOrBuilderList();
  /**
   * <code>repeated .pg_query.SummaryResult.FilterColumn filter_columns = 5;</code>
   */
  com.premiumminds.sonar.postgres.protobuf.SummaryResult.FilterColumnOrBuilder getFilterColumnsOrBuilder(
      int index);

  /**
   * <code>repeated string statement_types = 6;</code>
   * @return A list containing the statementTypes.
   */
  java.util.List<java.lang.String>
      getStatementTypesList();
  /**
   * <code>repeated string statement_types = 6;</code>
   * @return The count of statementTypes.
   */
  int getStatementTypesCount();
  /**
   * <code>repeated string statement_types = 6;</code>
   * @param index The index of the element to return.
   * @return The statementTypes at the given index.
   */
  java.lang.String getStatementTypes(int index);
  /**
   * <code>repeated string statement_types = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the statementTypes at the given index.
   */
  com.google.protobuf.ByteString
      getStatementTypesBytes(int index);

  /**
   * <pre>
   * optional, empty if truncation limit is -1 
   * </pre>
   *
   * <code>string truncated_query = 7;</code>
   * @return The truncatedQuery.
   */
  java.lang.String getTruncatedQuery();
  /**
   * <pre>
   * optional, empty if truncation limit is -1 
   * </pre>
   *
   * <code>string truncated_query = 7;</code>
   * @return The bytes for truncatedQuery.
   */
  com.google.protobuf.ByteString
      getTruncatedQueryBytes();
}
