// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface VarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.Var)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
   * @return Whether the xpr field is set.
   */
  boolean hasXpr();
  /**
   * <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
   * @return The xpr.
   */
  com.premiumminds.sonar.postgres.protobuf.Node getXpr();
  /**
   * <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getXprOrBuilder();

  /**
   * <code>int32 varno = 2 [json_name = "varno"];</code>
   * @return The varno.
   */
  int getVarno();

  /**
   * <code>int32 varattno = 3 [json_name = "varattno"];</code>
   * @return The varattno.
   */
  int getVarattno();

  /**
   * <code>uint32 vartype = 4 [json_name = "vartype"];</code>
   * @return The vartype.
   */
  int getVartype();

  /**
   * <code>int32 vartypmod = 5 [json_name = "vartypmod"];</code>
   * @return The vartypmod.
   */
  int getVartypmod();

  /**
   * <code>uint32 varcollid = 6 [json_name = "varcollid"];</code>
   * @return The varcollid.
   */
  int getVarcollid();

  /**
   * <code>repeated uint64 varnullingrels = 7 [json_name = "varnullingrels"];</code>
   * @return A list containing the varnullingrels.
   */
  java.util.List<java.lang.Long> getVarnullingrelsList();
  /**
   * <code>repeated uint64 varnullingrels = 7 [json_name = "varnullingrels"];</code>
   * @return The count of varnullingrels.
   */
  int getVarnullingrelsCount();
  /**
   * <code>repeated uint64 varnullingrels = 7 [json_name = "varnullingrels"];</code>
   * @param index The index of the element to return.
   * @return The varnullingrels at the given index.
   */
  long getVarnullingrels(int index);

  /**
   * <code>uint32 varlevelsup = 8 [json_name = "varlevelsup"];</code>
   * @return The varlevelsup.
   */
  int getVarlevelsup();

  /**
   * <code>.pg_query.VarReturningType varreturningtype = 9 [json_name = "varreturningtype"];</code>
   * @return The enum numeric value on the wire for varreturningtype.
   */
  int getVarreturningtypeValue();
  /**
   * <code>.pg_query.VarReturningType varreturningtype = 9 [json_name = "varreturningtype"];</code>
   * @return The varreturningtype.
   */
  com.premiumminds.sonar.postgres.protobuf.VarReturningType getVarreturningtype();

  /**
   * <code>int32 location = 10 [json_name = "location"];</code>
   * @return The location.
   */
  int getLocation();
}
