// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto
// Protobuf Java Version: 4.35.0

package com.premiumminds.sonar.postgres.protobuf;

@com.google.protobuf.Generated
public interface WithCheckOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.WithCheckOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.WCOKind kind = 1 [json_name = "kind"];</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.pg_query.WCOKind kind = 1 [json_name = "kind"];</code>
   * @return The kind.
   */
  com.premiumminds.sonar.postgres.protobuf.WCOKind getKind();

  /**
   * <code>string relname = 2 [json_name = "relname"];</code>
   * @return The relname.
   */
  java.lang.String getRelname();
  /**
   * <code>string relname = 2 [json_name = "relname"];</code>
   * @return The bytes for relname.
   */
  com.google.protobuf.ByteString
      getRelnameBytes();

  /**
   * <code>string polname = 3 [json_name = "polname"];</code>
   * @return The polname.
   */
  java.lang.String getPolname();
  /**
   * <code>string polname = 3 [json_name = "polname"];</code>
   * @return The bytes for polname.
   */
  com.google.protobuf.ByteString
      getPolnameBytes();

  /**
   * <code>.pg_query.Node qual = 4 [json_name = "qual"];</code>
   * @return Whether the qual field is set.
   */
  boolean hasQual();
  /**
   * <code>.pg_query.Node qual = 4 [json_name = "qual"];</code>
   * @return The qual.
   */
  com.premiumminds.sonar.postgres.protobuf.Node getQual();
  /**
   * <code>.pg_query.Node qual = 4 [json_name = "qual"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getQualOrBuilder();

  /**
   * <code>bool cascaded = 5 [json_name = "cascaded"];</code>
   * @return The cascaded.
   */
  boolean getCascaded();
}
